# Mod info
mod_name=Motion Capture - Emotecraft Compatibility Layer
mod_jar_name=MocapEmotecraftComp
mod_id=mocapemotecraftcomp
mod_group=net.mt1006.mocapcomp.emotecraft
mod_author1=mt1006
mod_author2=LOUDO
version=0.2
license=LGPL-3.0-only
homepage=https://modrinth.com/mod/mocap-ec-comp-layer
source_url=https://github.com/mt1006/mc-mocap-ec-comp
issue_tracker=https://github.com/mt1006/mc-mocap-ec-comp/issues
mod_description=Compatibility layer between Motion Capture and Emotecraft.

# Minecraft and Java
minecraft_version=1.21.10
java_version=21

# Requires
version_range_fabric=>=1.21.6
version_range_neoforge=[1.21.6,)

# Loaders
# https://github.com/FabricMC/fabric-loader/releases
# https://modrinth.com/mod/fabric-api/versions?c=release
# https://projects.neoforged.net/neoforged/neoforge
fabric_loader_version=0.18.4
fabric_api_version=0.138.4+1.21.10
neoforge_version=21.10.64

# Mappings
# https://parchmentmc.org/docs/getting-started
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Gradle dependencies
# https://github.com/FabricMC/fabric-loom/releases
# https://projects.neoforged.net/neoforged/ModDevGradle
fabric_loom_version=1.14-SNAPSHOT
neoforge_moddev_version=2.0.137

# Other dependencies
# https://modrinth.com/plugin/emotecraft/versions
# https://modrinth.com/mod/player-animation-library/versions
# https://modrinth.com/mod/motion-capture/versions
emotecraft_version=3.1.0-b.build.131
player_animation_library_version=1.1.3
mocap_version=1.4-alpha-10

# Gradle configuration
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.problems.report=false
