modLoader="javafml"
loaderVersion="*"
license="${license}"
issueTrackerURL="${issue_tracker}"

[[mods]]
modId="${mod_id}"
version="${version}"
displayName="${mod_name}"
displayURL="${homepage}"
logoFile="logo.png"
authors="${mod_author1}, ${mod_author2}"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.${mod_id}]]
	modId="neoforge"
	type="required"
	versionRange="*"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="minecraft"
	type="required"
	versionRange="${version_range_neoforge}"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="mocap"
	type="required"
	versionRange="[1.4-alpha-10,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.${mod_id}]]
	modId="emotecraft"
	type="required"
	versionRange="*"
	ordering="NONE"
	side="BOTH"
