plugins
{
	id "net.neoforged.moddev" version "${neoforge_moddev_version}"
}

repositories
{
	maven { url = "https://maven.kosmx.dev/" }
	maven { url = "https://repo.redlance.org/public/" }
	maven { url = "https://api.modrinth.com/maven/" }
}

neoForge
{
	version = neoforge_version
	parchment
	{
		minecraftVersion = parchment_minecraft
		mappingsVersion = parchment_version
	}

	runs
	{
		client { client() }
		server { server() }
	}

	dependencies
	{
		compileOnly "io.github.kosmx.emotes:emotesServer:${emotecraft_version}"
		implementation "maven.modrinth:emotecraft:${emotecraft_version}+${minecraft_version}-forge"
		implementation "maven.modrinth:playeranimator:${player_animation_library_version}+${minecraft_version}-forge"
		implementation "maven.modrinth:motion-capture:${mocap_version}-neoforge-${minecraft_version}"
		//implementation files("mocap-neoforge.jar")
	}

	mods
	{
		"${mod_id}" { sourceSet sourceSets.main }
	}
}
